import { IO } from 'fp-ts/IO'
import { iso, Newtype } from 'newtype-ts'

/**
 * Length of Uuid Seed
 */
export const VALID_UUID_LENGTH = 16 as const

/**
 * Newtype for Uuid string
 */
export interface Uuid extends Newtype<'Uuid', string> {}

export namespace Uuid {
  /**
   * Wrap and unwrap Uuid strings
   */
  export const { wrap, unwrap } = iso<Uuid>()
}

/**
 * UuidSeeds are tuples of 16 numbers, preferably generated by a cryptographically-safe number generator.
 */
export type UuidSeed = readonly [
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
]

/**
 * Environment type for generating UuidSeeds
 */
export interface UuidEnv {
  readonly randomUuidSeed: IO<UuidSeed>
}
