name: Main Flow

on:
  push:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: pnpm run build
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: workspace
          path: /home/runner/work/typed/typed

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@v2.1.1
        with:
          name: workspace
          path: /home/runner/work/typed/typed
      - run: pnpm run test

  circular:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@v2.1.1
        with:
          name: workspace
          path: /home/runner/work/typed/typed
      - run: pnpm run circular

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@v2.1.1
        with:
          name: workspace
          path: /home/runner/work/typed/typed
      - run: pnpm run lint

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@v2.1.1
        with:
          name: workspace
          path: /home/runner/work/typed/typed
      - run: pnpm run docs


  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [test, circular, lint, docs]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@v2.1.1
        with:
          name: workspace
          path: /home/runner/work/typed/typed
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm exec changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
