name: Main Flow

on:
  pull_request:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/setup-repo
        name: Setup Repo
      - run: pnpm run build
      - run: pnpm run circular

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/setup-repo
        name: Setup Repo
      - run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/setup-repo
        name: Setup Repo
      - run: pnpm run lint

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: ./.github/workflows/setup-repo
        name: Setup Repo
      - run: pnpm run docs
