name: Main Flow

on:
  pull_request:
    branches: [development]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.11.0]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: pnpm install
      - run: pnpm run build
      - uses: actions/upload-artifact@master
        with:
          name: workspace
          path: ./

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@master
        with:
          name: workspace
          path: ./
      - run: pnpm run test

  circular:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@master
        with:
          name: workspace
          path: ./
      - run: pnpm run circular

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@master
        with:
          name: workspace
          path: ./
      - run: pnpm run lint

  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.11.0]
    needs: [build]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        id: pnpm-install
        run: |
          corepack enable
      - uses: actions/download-artifact@master
        with:
          name: workspace
          path: ./
      - run: pnpm run docs
